title: Sean M. Lee, Ph.D. # your name (or website title) here
logo: "/images/logo3.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <a href="mailto:seanmlee87@gmail.com">seanmlee87@gmail.com</a>
  <br>
  <a href="https://scholar.google.com/citations?user=Cs00kqoAAAAJ&hl=en&oi=sra">Google Scholar</a>
  <br>
  <a href="https://www.twitter.com/sean_leezy">Twitter</a>
theme: jekyll-theme-minimal
google_analytics: G-VMZVX03DX0 # your Google Analytics tracking ID here
